input_shape:
    - 296

layers:
    - type: "FC"
      neurons: 200

    - type: "FC"
      neurons: 200

output_shape: 4

network_path: "./saved_models/fruit_collection/dqn/fc"
summaries_path: "./tensorflow_summaries/fruit_collection/dqn/fc/network_summary"
summaries_step: 100
restore_network: False
learning_rate: 0.00029
