epsilon_timesteps: 1000
starting_epsilon: 1
discount_factor: 0.95
batch_size: 35
memory_size: 10000
summaries_path: "./tensorflow_summaries/fruit_collection/dqn/fc/reinforce_summary"
replace_frequency: 100
update_steps: 20
