input_shape:
    - 17
    - 32
    - 32

output_shape: 4

layers:
    - type: "CNN"
      in_channels: 17
      out_channels: 32
      kernel_size: 5
      stride: 1
      padding: 2

    - type: "BatchNorm2d"
      size: 32

    - type: "MaxPool2d"
      kernel_size: 4
      stride: 2

    - type: "CNN"
      in_channels: 32
      out_channels: 64
      kernel_size: 5
      stride: 1
      padding: 2

    - type: "BatchNorm2d"
      size: 64

    - type: "MaxPool2d"
      kernel_size: 4
      stride: 2


    - type: "FC"
      neurons: 256

    - type: "FC"
      neurons: 64


network_path: "./saved_models/pysc2/collect_shards/dqn/v1"
summaries_path: "./tensorflow_summaries/pysc2/collect_shards/dqn/v1/network_summary"
summaries_step: 50000
restore_network: True
learning_rate: 0.0002
save_steps: 100
