decay_steps: 10000
starting_epsilon: 1
discount_factor: 0.99
batch_size: 32
memory_size: 10000
summaries_path: "./tensorflow_summaries/pysc2/collect_shards/dqn/v1/reinforce_summary"
replace_frequency: 4000
update_steps: 10
beta_timesteps: 1000000
