networks:
  - name: "bonus"
    layers:
        - 50
        - 50

  - name: "dealt_damage"
    layers:
        - 50
        - 50

  - name: "friendly_kill"
    layers:
        - 50
        - 50

  - name: "took_damage"
    layers:
        - 50
        - 50



input_shape:
    - 40
    - 40
    - 6

layers:
    - 100

output_shape:
    - 4

network_path: "./saved_models/SkyRTS/multi-step/hra/v1/network"
summaries_path: "./tensorflow_summaries/SkyRTS/multi-step/hra/v1/network_summary"
summaries_step: 150
restore_network: True
save_steps: 100
