decay_steps: 300
starting_epsilon: 1
discount_factor: 0.99
batch_size: 35
memory_size: 100000
summaries_path: "./tensorflow_summaries/pysc2/collect_shards/hra/v1/reinforce_summary"
update_frequency: 200
update_steps: 20
