input_shape:
    - 4

networks:
  - name: "PoleAngle"
    layers:
      - type: "FC"
        neurons: 50
      - type: "FC"
        neurons: 50

  - name: "CartPosition"
    layers:
        - type: "FC"
          neurons: 50
        - type: "FC"
          neurons: 50

  - name: "Terminal"
    layers:
        - type: "FC"
          neurons: 50
        - type: "FC"
          neurons: 50



output_shape: 2

network_path: "./saved_models/cart_pole/hra/v1/network.ckpt"
summaries_path: "./tensorflow_summaries/cart_pole/hra/v1/network_summary"
summaries_step: 100
restore_network: False
