input_shape:
    - 110

layers:
    - 200
    - 200

output_shape:
    - 4

network_path: "./saved_models/fruit_collection/dqn/v1.ckpt"
summaries_path: "./tensorflow_summaries/fruit_collection/dqn/v1/network_summary"
summaries_step: 100
restore_network: False
