decay_steps: 10
starting_epsilon: 1
discount_factor: 0.95
batch_size: 35
memory_size: 10000
summaries_path: "./tensorflow_summaries/SkyRTS/tower_capture/dqn/v1/reinforce_summary"
update_frequency: 10
